name: fmesh

channels:
  - conda-forge
dependencies:
  - python<=3.9
  - numpy
  - netCDF4
  - fastkml
  - cartopy
  - cmake
  - geopy
  - pyyaml
  - jigsaw
  - jigsawpy
  - lxml
  - pip:
    - art



