
# Builds and publishes a Docker container to the GitHub Container Registry 
# and a Singularity Container to the Singularity Registry
#
# Paul Gierz, October 2022
name: Containerize

on:
  push:
    branches:
      # - 'main'
      - 'containerization'  # For testing, to be removed.

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  apptainer:  # Former name of singularity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show some diagnostics
        run: |
          env
          pwd
          ls -ratl
      - name: Setup apptainer
        uses: eWaterCycle/setup-apptainer@v1.0.1
      - name: Build Apptainer Container
        run: |
          apptainer build ${GITHUB_REPOSITORY}.sif apptainer.def 
      # Probably need to authenticate first...
      - name: Push Container 
        run: 
          apptainer push ${GITHUB_REPOSITORY}.sif library://FESOM/fmesh/${GITHUB_REPOSITORY}.sif:latest 
